recipes/apache2.rb
templates/default/web_app.conf.erb

Rolls back #36 
Fixes #42
`Authorization` header should not be removed. It's enough to disable `auth_basic` module.
cc:\ @linc01n @martianus

Fixed HTTP authentication

---

attributes/default.rb
libraries/stash.rb

`Chef::Recipe::Stash.settings` method is going to set default settings:
```
settings ||= node['stash']
settings['database']['port'] ||= default_database_port settings['database']['type']
settings['database']['testInterval'] ||= 2
```
But it will never be done because the node will always have these attributes specified in `attributes/default.rb`. 
For example, even if we set `['database']['type'] = 'postgresql'`, the port will be "3306" anyway. So that, these attributes should not be specified in attribute file.
This method should be a class method, instead of an instance method. Otherwise, it can not be called from `Chef::Recipe::Stash.settings` method 
While copying `settings ||= node['stash']` it should be also converted to Hash object, becouse Node object is read-only and overriding …

Fixes for the Stash library

---

recipes/backup_client.rb

The `ark` resource requires `rsync` package to be installed.
It fixes the next error (reproduced on "centos6" and "stash" cookbook version 3.12.1):
```
...
==> centos6: Mixlib::ShellOut::ShellCommandFailed
==> centos6: ------------------------------------
==> centos6: execute[unpack /var/chef/cache/stash-backup-client-1.5.0.zip] (/tmp/vagrant-chef-3/chef-solo-1/cookbooks/ark/providers/default.rb line 55) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '127'
==> centos6:
==> centos6: ---- Begin output of unzip -q -u -o /var/chef/cache/stash-backup-client-1.5.0.zip -d /tmp/d20141111-3706-192msdu && rsync -a /tmp/d20141111-3706-192msdu/*/ /opt/atlassian/stash-backup-client-1.5.0 && rm -rf /tmp/d20141111-3706-192msdu ----
==> centos6:
==> …
```

Fix for "sh: 'rsync' no such file or directory" on RHEL-like systems

---

Berksfile

Since there is an outdated directive in Berksfile, we have the following warning from the resent "berks":
>DEPRECATED: Your Berksfile contains a site location pointing to the Opscode Community Site (site :opscode). Site locations have been replaced by the source location. Change this to: 'source "https://supermarket.chef.io"' to remove this warning. For more information visit https://github.com/berkshelf/berkshelf/wiki/deprecated-locations
So, this pull-request fixes that warning.

Fixed deprecation warning from Berkshelf

---

recipes/configuration.rb

recipes/configuration.rb:24:7: C: Indent the first parameter one step
more than the previous line.
:database   => settings['database'],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Fix rubocop offenses

---

README.md
attributes/default.rb

* Added support of Stash versions 3.8.1, 3.9.1, 3.9.2, 3.10.0
* Default Stash version is set to 3.10.0
* Added support of Stash backup client versions 1.9.0, 1.9.1
* Default Stash Backup Client version is set to 1.9.1
cc:\ @linc01n

Add support of Stash versions 3.8.1, 3.9.1, 3.9.2, 3.10.0

---

templates/default/setenv.sh.erb

Use proper setenv.sh format for v3.8+.

---

templates/default/3.8+/setenv.sh.erb

Set umask to 0027 for more secure file creation

---

Gemfile
recipes/backup_client.rb

Create backup folder recusively

---

attributes/default.rb
recipes/configuration.rb

- set directory to right permission
If users are upgrading from 3.x cookbook to 4.x, we should not change the repo data path.
Users may have other external script using that path.

Set home path to 3.x default when it exists

---

templates/default/backup-diy-vars.sh.erb

This PR updates the config template according to the latest changes in master branch of repo "Stash DIY backup": https://bitbucket.org/atlassianlabs/atlassian-stash-diy-backup
In particular, a new variable `CURL_OPTIONS` was added to `backup-diy-vars.sh`.

Update the template for DIY backup

---

.kitchen.yml

All Vagrant boxes from "chef" account on Atlas have been moved to the "bento" namespace:
https://atlas.hashicorp.com/chef
P.s. By the way, is it still reasonable to freeze Chef Client version in `.kitchen.yml`?
```
require_chef_omnibus: 11.16.2
```
https://github.com/bflad/chef-stash/blob/8c8dda6b5b25873bd87a8e5c2de75168a1b05adc/.kitchen.yml#L4

.kitchen.yml: Rename Vagrant boxes "chef" -> "bento"

---

.kitchen.yml

We changed the default from `mysql` to `postgresql` after cookbook 4.0 release.
So we need to specify to use mysql database during `kitchen test`

Set database type when running mysql suite

---

templates/default/web_app.conf.erb

*Similar changes were merged to JIRA and Confluence cookbooks:*
https://github.com/afklm/jira/pull/39
https://github.com/parallels-cookbooks/confluence/pull/73
We use Apache web server in the front of Tomcat.
Since we configure SSL in Apache by default, we can also add a rewrite rule to the virtual host configuration in order to force HTTPS.
And we don't need to configure proxy for HTTP-based virtual host anymore.

Redirect HTTP to HTTPS

---

README.md
attributes/default.rb
recipes/linux_standalone.rb
recipes/tomcat_configuration.rb
spec/default_spec.rb
templates/default/server.xml.erb
test/integration/mysql/serverspec/linux_standalone_spec.rb
test/integration/mysql/serverspec/service_init_spec.rb
test/integration/postgresql/serverspec/linux_standalone_spec.rb
test/integration/postgresql/serverspec/service_init_spec.rb

*The similar PRs were merged to JIRA and Confluence cookbooks: *
afklm/jira#30 
https://github.com/parallels-cookbooks/confluence/pull/68
Production instances of Bitbucket Server (and Stash) usually use some web server as a reverse proxy at the front of Tomcat.
In this cookbook we also configure Apache web server for these needs.
So, since https is actually terminating on the Apache side, there are no needs to manage keystore
and configure TLS/SSL on the Tomcat side.
*UPDATE:*
Closes #56

Disable https on the Tomcat side

---

recipes/backup_client.rb

https://confluence.atlassian.com/bitbucketserver/using-the-bitbucket-server-backup-client-776640064.html#UsingtheBitbucketServerBackupClient-BackingupBitbucketServerusingtheclient
the example shows 
```
cd <path/to/backup-config.properties file>
java -jar <path/to/bitbucket-backup-client.jar>
```
/cc @legal90

Go to the directory contains backup.properties

---

metadata.rb
recipes/apache2.rb

In cookbook apache2 v3.2.0 the attribute was changed and renamed:
`node.default['apache']['listen_ports']` -> `node.default['apache']['listen']`
This change causes the following error with `apache2` cookbook 3.2.0 and higher:
```
NoMethodError
-------------
undefined method `include?' for nil:NilClass
Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/stash/recipes/apache2.rb:1:in `from_file'
/tmp/kitchen/cache/cookbooks/stash/recipes/default.rb:16:in `from_file'
Relevant File Content:
----------------------
/tmp/kitchen/cache/cookbooks/stash/recipes/apache2.rb:
1>> node.set['apache']['listen_ports'] = node['apache']['listen_ports'] + [node['stash']['apache2']['port']] unless node['apache']['listen_ports'].include?(node['stash']['apache2']['port'])
2: …
```

Fix apache listen ports attribute

---

metadata.rb
recipes/apache2.rb

Remove apache2 pinning and wrap it inside a `begin...rescue` block
Related to #148 
/cc @bflad @legal90

Support multiple apache2 versions

---

recipes/tomcat_configuration.rb
templates/default/bitbucket/set-bitbucket-home.sh.erb

The setup scripts in $BITBUCKET_HOME/bin were refactored and now they call set-bitbucket-home.sh to set BITBUCKET_HOME and set-bitbucket-user.sh to set BITBUCKET_USER instead of user.sh.
Without this patch, a Bitbucket instance starts up under root. A bundled Elasticsearch instance can't run as root and fails to start. That's the reason code search doesn't work. You get behaviour like described here: https://jira.atlassian.com/browse/BSERV-8763 (Search is currently unavailable)
We need to have $BITBUCKET_HOME/bin/set-bitbucket-home.sh and $BITBUCKET_HOME/bin/set-bitbucket-user.sh instead of  $BITBUCKET_HOME/bin/user.sh for Bitbucket 4.6.0 and higher.
I tested the change with Bitbucket 4.6.2.
Fixes #156
@linc01n @bflad Please have a look

Bitbucket 4.6 needs set-bitbucket-home.sh and set-bitbucket-user.sh

---

templates/default/bitbucket/bitbucket.init.erb

After merging #157 I've converged a new bitbucket instance, and it seems that patch isn't enough to bring the code search up.
When I start Bitbucket manually, I get 'cannot stat' error and elasticsearch fails as log4j isn't configured properly (elasticsearch/config-template/ contains logging configuration). The result is the same -- 'Search is unavailable'.
```
/etc/init.d/bitbucket start
-------------------------------------------------------------------------------
Starting Atlassian Bitbucket and bundled Elasticsearch
To start Atlassian Bitbucket on its own, run start-webapp.sh instead
-------------------------------------------------------------------------------
Starting Elasticsearch bundled with Atlassian Bitbucket
BITBUCKET_HOME set to /var/atlassian/application-data/bitbucket …
```

Run start-bitbucket.sh with the full path in Bitbucket init script

---

templates/default/web_app.conf.erb

Current Apache template doesn't allow to access /server-status (https://httpd.apache.org/docs/2.4/mod/mod_status.html) by any monitoring system.
This PR resolve this problem and doesn't affect security because you can disable /server-status location in httpd.conf file.
The same i did and for https://github.com/afklm/jira/pull/92 and https://github.com/parallels-cookbooks/confluence/pull/128

Don't redirect /server-status for monitoring systems

---

attributes/default.rb
templates/default/3.8+/web.xml
templates/default/bitbucket/web.xml
templates/default/web-tomcat7.xml.erb
templates/default/web.xml.erb

In order to be able to dynamically control the timeout of the tomcat's session, I moved it to an attribute.

Enable setting the session timeout
